function Hd = code_design
%CODE_DESIGN 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
% Generated on: 23-May-2021 15:38:08

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 30;  % Sampling Frequency

N      = 32;  % Order
Fstop1 = 2;   % First Stopband Frequency
Fpass1 = 4;   % First Passband Frequency
Fpass2 = 7;   % Second Passband Frequency
Fstop2 = 10;  % Second Stopband Frequency
Wstop1 = 1;   % First Stopband Weight
Wpass  = 1;   % Passband Weight
Wstop2 = 1;   % Second Stopband Weight
dens   = 20;  % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 0 1 1 0 ...
           0], [Wstop1 Wpass Wstop2], {dens});
Hd = dfilt.dffir(b);

% [EOF]
